# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
loaderVersion="[1,)" #mandatory
license="MIT"

[[mods]]
modId="landingmud"
version="${mod_version}" #mandatory
displayName="Landing Mud" #mandatory

authors="meteoritel"

# The description text for the mod (multi line!) (#mandatory)
description='''
从高处落在泥巴上减免80%伤害，并概率转化泥巴为可疑方块
'''

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
#[[mixins]]
#config="${mod_id}.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.landingmud]] #optional
    # the modid of the dependency
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[21.1,)" #mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT, or SERVER
    side="BOTH"

# Here's another dependency
[[dependencies.landingmud]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

